-
  name: Testing DSV
  hosts: gtdocktest
  vars:
    # client_creds: "{{ lookup('url','https://thrasher.secretsvaultcloud.com/v1/clients/bootstrap/f5470e29-a6e9-423d-b723-c01487323cfb') }}"
    #secret: "{{ lookup('community.general.dsv', '/github/testuser', client_id='c08f968b-c660-487e-92a9-ffddaf71de12', client_secret='KPkiZaKj-8kHfo3ebpn7LxwP27odhXkqE4pB2-EhPkk', tenant='thrasher') }}"
    #clientId: 'clientId={{ client_creds["clientId"] }}'
    #clientSecret: 'clientSecret={{ client_creds["clientSecret"] }}'
    #secret: "{{ lookup('community.general.dsv', '/github/testuser', clientId, clientSecret, tenant='thrasher') }}"
    #mydate: "{{ lookup('pipe','date +%Y%m%d%H%M%S**.%5N**') }}"
  tasks:
    - name: Get DSV Creds
      uri: 
        url: https://thrasher.secretsvaultcloud.com/v1/clients/bootstrap/e6425333-8f84-42fb-9692-260d892b5678
        #return_content: yes
      register: client_out
    - debug: var=ansible_python_interpreter
    - debug: var=ansible_python_version
    - ansible.builtin.debug:
        #msg: 'the username is: {{ secret["data"]["username"] }} and the password is: {{ secret["data"]["password"] }}'
        #msg: 'Client_creds is: {{ client_creds }}'
        # msg: 'Date is: {{ mydate }}'
        msg: 'ClientId: {{ client_out["json"]["clientId"] }}'
    - ansible.builtin.debug:
        #msg: 'the username is: {{ secret["data"]["username"] }} and the password is: {{ secret["data"]["password"] }}'
        #msg: 'ClientId is: {{ clientId }}'
        msg: 'ClientSecret: {{ client_out["json"]["clientSecret"] }}'
    - ansible.builtin.debug:
        #msg: "client creds from URL: {{ lookup('url','https://thrasher.secretsvaultcloud.com/v1/clients/bootstrap/baeb03ac-57ab-4137-b132-167482cd5654') }}"
        #msg: "The clientId is: {{ client_creds['clientId'] }}"
        #msg: 'ClientSecret is: {{ clientSecret }}'
        #msg: 'Date2 is: {{ mydate }}'